substitutions:
  _IMG: vanity
  _REG: us.gcr.io
tags:
  - $SHORT_SHA
  - $COMMIT_SHA
steps:
  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - -c=.
      - -f=Dockerfile
      - -d=$_REG/$PROJECT_ID/$_IMG:latest
      - -d=$_REG/$PROJECT_ID/$_IMG:$TAG_NAME
      # - -d=index.docker.io/seankhliao/$_IMG:latest
      # - -d=index.docker.io/seankhliao/$_IMG:$TAG_NAME
      - --reproducible
      - --single-snapshot
