// Code generated by generate.go DO NOT EDIT.
package main

const (
        tmplStr = `<!DOCTYPE html>
<html lang="en">
  <meta
    name="go-import"
    content="go.seankhliao.com/{{ .Repo }}
        git https://github.com/seankhliao/{{ .Repo }}"
  />
  <meta
    name="go-source"
    content="go.seankhliao.com/{{ .Repo }}
        https://github.com/seankhliao/{{ .Repo }}
        https://github.com/seankhliao/{{ .Repo }}/tree/master{/dir}
        https://github.com/seankhliao/{{ .Repo }}/blob/master{/dir}/{file}#L{line}"
  />
  <meta http-equiv="refresh" content="5;url=https://godoc.org/go.seankhliao.com/{{ .Repo }}" />
  <title>go.seankhliao.com/{{ .Repo }}</title>
  <p>
    source:
    <a
      href="https://github.com/seankhliao/{{ .Repo }}"
      ping="https://statslogger.seankhliao.com/form?trigger=ping&src=go.seankhliao.com/{{ .Repo }}&dst=github.com/seankhliao/{{ .Repo }}"
    >
      github</a
    >
  </p>
  <p>
    docs:
    <a
      href="https://godoc.org/go.seankhliao.com/{{ .Repo }}"
      ping="https://statslogger.seankhliao.com/form?trigger=ping&src=go.seankhliao.com/{{ .Repo }}&dst=godoc.org/go.seankhliao.com/{{ .Repo }}"
    >
      godoc</a
    >
  </p>
</html>
`
)
