apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert.yaml
  - service.yaml
  - deployment.yaml
images:
  - name: us.gcr.io/com-seankhliao/vanity
    # newTag: IMAGE_TAG
